### ISSUE TITLE
Chapter 2: Basic TCP Listener Example

### ISSUE THREAD

**Issue by chrisVillanueva** [gruberb/practical-rust-book#1]
Hi.

I didn't see a basic TCP Listener example in the example source code.  I understand it only prints to terminal.  But I think adding it to the project will show the progression from bare metal code to the `minimal-tcp` example.  As a reader, it helps me follow the manuscript and see the progression.  A reader may want  to see the stream working in terminal:

![Screenshot from 2021-03-27 10-10-13](https://user-images.githubusercontent.com/1554280/112724113-060cef80-8ee8-11eb-8bc4-7b00f69d5be9.png)

Not sure whether you accept PRs at this point.  I added the code in my fork to align with the book example:

https://github.com/chrisVillanueva/practical-rust-book/tree/minimal-tcp-terminal/ch_02/minimal-tcp-terminal

**Comment by gruberb** [comment]
Hey @chrisVillanueva ! Thanks for pointing it out! I have a basic tcp example ("minimal tcp"). So is your point that there should be an even simpler version of it? Instead of answering a request, just printing it?

**Comment by chrisVillanueva** [comment]
Hi @gruberb.

Thanks for the follow up.  

Yes, you're response is correct.  I think a working example to print to terminal and sharing a screenshot will aid the reader's understanding.  I say this because you preceded the code example with Figure 2.4--which provides very useful information about the client-server interaction with Rust.  In my mind, I needed to run the code example in terminal to reason about the steps in Figure 2.4. 

Hope this helps.  

Chris
