### ISSUE TITLE
Chapter 2: Minimal Tokio TCP Warnings

### ISSUE THREAD

**Issue by chrisVillanueva** [gruberb/practical-rust-book#2]
`minimal-tokio-tcp` produces warnings with `cargo build` command.

![Screenshot from 2021-03-27 12-38-55](https://user-images.githubusercontent.com/1554280/112727596-93a50b00-8ef9-11eb-8722-9daaeffabf57.png)

**Comment by gruberb** [comment]
Thanks, fixed it!
